/**:
  ros__parameters:
    global_frame: map
    # Lidar settings
    use_lidar: false
    # QoS settings
    depth_qos: "SENSOR_DATA"
    color_qos: "SENSOR_DATA"
    # Map clearing settings
    map_clearing_frame_id: "base_link"
    # Rviz visualization
    slice_visualization_attachment_frame_id: "base_link"

    static_mapper:
      esdf_slice_height: 0.1
      esdf_slice_min_height: 0.1
      esdf_slice_max_height: 0.65
      # do not send ceiling:
      mesh_streamer_exclusion_height_m: 1.4
      mesh_streamer_exclusion_radius_m: 5.0

    dynamic_mapper:
      esdf_slice_height: 0.0
      esdf_slice_min_height: 0.1
      esdf_slice_max_height: 0.65
