%YAML 1.2
# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
---
##########################################
# This is a placeholder                  #
# Actual common atlas is defined in      #
# type_adapter_nitros_context_graph.yaml #
##########################################
name: atlas
components:
- name: base_link
  type: nvidia::isaac::PoseTreeFrame
  parameters:
    pose_tree: global_pose_tree/pose_tree
- name: segway_imu
  type: nvidia::isaac::PoseTreeFrame
  parameters:
    pose_tree: global_pose_tree/pose_tree
- name: pose_tree
  type: nvidia::isaac::PoseTree
- type: nvidia::isaac::PoseTreeSetup
  parameters:
    pose_tree: pose_tree
- name: frontend
  type: nvidia::isaac::AtlasFrontend
  parameters:
    pose_tree: pose_tree
    composite_schema_server: global_pose_tree/composite_schema_server
---
name: segway_driver
components:
- name: rx_command
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- name: tx_encoder_ticks
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 1
    policy: 0
- name: tx_imu
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 1
    policy: 0
- name: tx_ego_motion
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 1
    policy: 0
- name: tx_battery_state
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    policy: 0
- name: allocator
  type: nvidia::gxf::BlockMemoryPool
  parameters:
    storage_type: 0
    block_size: 768
    num_blocks: 200
- name: segway_driver
  type: nvidia::isaac::SegwayDriver
  parameters:
    rx_command: rx_command
    tx_encoder_ticks: tx_encoder_ticks
    tx_imu: tx_imu
    tx_ego_motion: tx_ego_motion
    tx_battery_state: tx_battery_state
    allocator: allocator
    segway_imu_frame: atlas/segway_imu
    segway_ego_motion_child_frame: atlas/base_link
    atlas_frontend: atlas/frontend
- type: nvidia::gxf::PeriodicSchedulingTerm
  parameters:
    transmitter: tx_ego_motion
    recess_period: 100Hz
- type: nvidia::gxf::MemoryAvailableSchedulingTerm
  parameters:
    allocator: allocator
    min_blocks: 1
---
name: sink_odometry
components:
- name: signal
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: signal
    min_size: 1
- name: sink
  type: nvidia::isaac_ros::MessageRelay
  parameters:
    source: signal
---
name: sink_encoder_ticks
components:
- name: signal
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: signal
    min_size: 1
- name: sink
  type: nvidia::isaac_ros::MessageRelay
  parameters:
    source: signal
---
name: sink_battery_state
components:
- name: signal
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: signal
    min_size: 1
- name: sink
  type: nvidia::isaac_ros::MessageRelay
  parameters:
    source: signal
---
name: sink_imu
components:
- name: signal
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
    policy: 0
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: signal
    min_size: 1
- name: sink
  type: nvidia::isaac_ros::MessageRelay
  parameters:
    source: signal
---
components:
- name: edge1
  type: nvidia::gxf::Connection
  parameters:
    source: segway_driver/tx_encoder_ticks
    target: sink_encoder_ticks/signal
- name: edge2
  type: nvidia::gxf::Connection
  parameters:
    source: segway_driver/tx_imu
    target: sink_imu/signal
- name: edge3
  type: nvidia::gxf::Connection
  parameters:
    source: segway_driver/tx_ego_motion
    target: sink_odometry/signal
- name: edge4
  type: nvidia::gxf::Connection
  parameters:
    source: segway_driver/tx_battery_state
    target: sink_battery_state/signal
---
components:
- name: clock
  type: nvidia::gxf::RealtimeClock
- type: nvidia::gxf::GreedyScheduler
  parameters:
    clock: clock
    stop_on_deadlock: false
    check_recession_period_us: 100
- type: nvidia::gxf::JobStatistics
  parameters:
    clock: clock
